spring:
  rabbitmq:
    addresses: 172.16.2.23:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000

    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10

  datasource:
    url: jdbc:mysql://www.biodwhu.cn/biod_server_diagnose
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.163.com
    port: 25
    username: biodwhu@163.com
    password: biodwhu503
    default-encoding: UTF-8
    properties:
      msil:
        smtp:
          auth: true
          ssl:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8090