spring:
  rabbitmq:
    addresses: 172.16.2.23:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  #数据库连接配置 Druid连接池
  datasource:
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.92.212.129/biod_server_model
    username: root
    password: 123456
    dbcp2:
      # 初始化，最小，最大连接数
      initial-size: 3
      min-idle: 3
      max-total: 18
      # 获取数据库连接等待的超时时间
      max-wait-millis: 200
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 一个空闲连接最少空闲多久后可被清除，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # MySql游标优化
      pool-prepared-statements: true
      max-open-prepared-statements: 20
    # 配置监控统计拦截的filters
    filters: stat,wall,log4j

mybatis:
  configuration:
    map-underscore-to-camel-case: true